/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maicon
 */
public class telaCadastroUser extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroUser
     */
    public telaCadastroUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCadastroUser = new javax.swing.JTextField();
        senhaCadastroUser = new javax.swing.JTextField();
        adminCadastroUser = new javax.swing.JRadioButton();
        comumCadastroUser = new javax.swing.JRadioButton();
        ok_cadastroUser = new javax.swing.JButton();
        cancel_cadastroUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeCadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadastroUserActionPerformed(evt);
            }
        });

        senhaCadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCadastroUserActionPerformed(evt);
            }
        });

        adminCadastroUser.setText("Admin");
        adminCadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCadastroUserActionPerformed(evt);
            }
        });

        comumCadastroUser.setText("Comum");
        comumCadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comumCadastroUserActionPerformed(evt);
            }
        });

        ok_cadastroUser.setText("OK");

        cancel_cadastroUser.setText("CANCELAR");
        cancel_cadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_cadastroUserActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(senhaCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(adminCadastroUser)
                            .addGap(18, 18, 18)
                            .addComponent(comumCadastroUser))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ok_cadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancel_cadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminCadastroUser)
                    .addComponent(comumCadastroUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(nomeCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_cadastroUser)
                    .addComponent(cancel_cadastroUser))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(460, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadastroUserActionPerformed

    private void senhaCadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCadastroUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCadastroUserActionPerformed

    private void comumCadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comumCadastroUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comumCadastroUserActionPerformed

    private void cancel_cadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_cadastroUserActionPerformed
        // TODO add your handling code here:
        telaPrincipal principal = new telaPrincipal();//objeto instanciado
        principal.setVisible(true);//objeto chamado com seu método e parâmetro
        dispose();//fecha a tela anterior
    }//GEN-LAST:event_cancel_cadastroUserActionPerformed

    private void adminCadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCadastroUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminCadastroUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminCadastroUser;
    private javax.swing.JButton cancel_cadastroUser;
    private javax.swing.JRadioButton comumCadastroUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nomeCadastroUser;
    private javax.swing.JButton ok_cadastroUser;
    private javax.swing.JTextField senhaCadastroUser;
    // End of variables declaration//GEN-END:variables
}
